### PR TITLE
Dependencies and Eslint update

### PR DESCRIPTION
**Pull request by Goldziher**
This PR updates the project dependencies and the eslint configs, and resolves all eslint / type issues.

### CODE REVIEW

**Comment by horiuchi** [comment]
I think the direction of this proposal is good.
However, the unit-test does not pass on node v10, so please fix that.

**Comment by horiuchi** [comment]
But now, please wait a bit for major changes.
Because I think the plugin interface change to use the ESTree AST instead of the TypeScript AST.

If the plugin depends on TypeScript AST, it would have to always refer to the same version of TypeScript as the main dtsgenerator. However, that would make it difficult to maintain each of the main and all plugins, so we want the plugin interface to be independent of the TypeScript version.

**Comment by Goldziher** [comment]
@horiuchi - i dont understand regarding the EStree parser, how is this related to this PR? I can change eslint to use EStree but that will degrade the linting quite dramatically. I can also use a sub tsconfig.json file for eslint only and extend the project wide tsconfig or ignore it.

**Comment by Goldziher** [comment]
I pushed a fix to the tests (was the target in tsConfig).

**Comment by horiuchi** [comment]
The only thing I would like to change is the interface to the plugin, not the contents of the dtsgenerator.

For this PR, there are too many changes, and I would like to see it broken up into smaller changes.

**Comment by Goldziher** [comment]
I still don't understand what you would like me to do. I'm closing this PR if its not going to be merged.

**Comment by horiuchi** [comment]
I'm very excited about these `eslint` configuration changes, so I hope you'll make a PR just for that first.

**Pull request closed without merging**
