### PR TITLE
Avoid error when using `responses` & `requestBodies` components

### PR DESCRIPTION
**Pull request by adriengibrat**
Hi,

I consistently got parsing errors:
```
The $ref targets root is not found: #/components/responses/xxx
The $ref targets root is not found: #/components/requestBodies/xxx
```
when my openAPI files contains `responses` & `requestBodies` components.

here is a patch that fix the issue and still pass all tests ;)

### CODE REVIEW

**Comment by adriengibrat** [comment]
Example to reproduce the error I'm refering to:
```yaml
openapi: 3.0.2
info:
  description: example with response & requestBobies components
  title: test
  version: 0.0.1
paths:
  /endpoint:
    post:
      operationId: createResource
      summary: Create a resource
      requestBody:
        $ref: '#/components/requestBodies/ResourceCreationRequest'
      responses:
        '200':
          $ref: '#/components/responses/201Created'
        '400':
          $ref: '#/components/responses/400Invalid'
components:

  schemas:
    Resource:
      type: object
      properties:
        status:
          type: string

  requestBodies:
    ResourceCreationRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Resource'

  responses:
    201Created:
      description: Created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Resource'
    400Invalid:
      description: Invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
  
```

**Comment by adriengibrat** [comment]
DO NOT Merge... this PR creates duplicates! 
I'm working on a better patch.

**Comment by horiuchi** [comment]
@adriengibrat Sorry, this was the dtsgenerator's bug.
The `$ref` was not handled correctly when there was a number at the beginning of the identifier.

**Comment by adriengibrat** [comment]
Great! thanks

I knew my patch was kind of really hacky...
I'll test the v2.3.2

I also encoutered bugs when using the https://apitools.dev/swagger-cli bundle, I'll try to report it properly in a github issue if it still happend!

**Pull request closed without merging**
