### PR TITLE
full support for minItems & maxItems

### LINKED ISSUE #476: Feature: full support for `minItems` & `maxItems`
Hi!

First i want to thank you for your work, this project has been so useful in our company projects!
We developed a number of improvements internally and we'd like to contribute back to the project and also avoid using patches over your module in the future.
Every change we developed has corresponding tests, some have corresponding options flags when really necessary, and to possibly avoid breaking changes. 

For reference, in addition to this one, that's what we have in store (you can always have a look here: https://github.com/medfreeman/dtsgenerator/network):
- support for `additionalItems`
- fix specific typescript transforms in plugins not producing changes at all (by changing the way the `generate` handles writing transform results)
- fix nested `oneOf` & `anyOf` that can produce incorrect children
- have free-form objects generate a index signature instead of `unknown`
- changes about the handling of `not` --> `void` types that can be incorrect in specific scenarios
- `patternProperties` possibly generating two index signatures, that don't pass strict mode (atm i disabled the relevant code internally and did not come up with a fix)

This will probably be kept private, unless it can be of interest to you, but we have also developed two plugins internally:
- one that adds an `export` keyword before each top-level `declare namespace` statement
- one that extracts generated interface & namespace names and their possible correspondence to schema ids

### PR DESCRIPTION
**Pull request by medfreeman**
closes #476

### CODE REVIEW

**Comment by horiuchi** [comment]
Thank you for your contribution! 👍 
So awesome feature!

I think the `strictArraySize` option is unnecessary and should always be enabled. What do you think?

**Comment by medfreeman** [comment]
Thanks!

The thing is this feature can complicate consumer's code a bit, because in strict mode a tuple will be incompatible with an array.
As long as you're happy with this, i'm happy either way.
There's a case for not adding too much options too!

**Comment by medfreeman** [comment]
Tell me what you choose and i'll remove the option and the test infra change if necessary.
Thanks!

**Comment by horiuchi** [comment]
I don't want to add too many options either, so please remove the options.

The complexity of the type is not a problem for me.
I'd rather have the TypeScript compiler warn us more correctly by type definition.

**Comment by medfreeman** [comment]
it's ready!

**Comment by horiuchi** [comment]
@medfreeman Thank you for awesome work! 👍

**Comment by crizo23** [comment]
@medfreeman @horiuchi 

The one negative I can see of the tuples is that for types defined as:
`      "ArrayOfFoos": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Foo"
        },
        "minItems": 0,
        "maxItems": 500
      },`

results in:
`export type ArrayOfFoos = [
  Foo ?,
  Foo ?,
  Foo ?,
  Foo ?,
  ..all the way to 500
]; `

resulting in a rather large type.
I understand that this provides a type that is restricted by min/max length. Was there any way to do this differently?

**Comment by horiuchi** [comment]
@crizo23 Thank you for your information. That's a problem.

One idea would be to simply revert to an unlimited number of types as before if `maxItems` exceeds some threshold, although it would be a loose definition of a type.
For example, if the threshold is set to 5, then up to `maxItems` of 5, the type will be generated as usual for `[Foo, Foo, Foo, Foo, Foo]` and `maxItems`, but when `maxItems` exceeds the threshold, the type will always be generated as `[Foo, Foo, Foo, Foo, Foo, ... Foo]`.

**Comment by crizo23** [comment]
> @crizo23 Thank you for your information. That's a problem.
> 
> One idea would be to simply revert to an unlimited number of types as before if `maxItems` exceeds some threshold, although it would be a loose definition of a type.
> For example, if the threshold is set to 5, then up to `maxItems` of 5, the type will be generated as usual for `[Foo, Foo, Foo, Foo, Foo]` and `maxItems`, but when `maxItems` exceeds the threshold, the type will always be generated as `[Foo, Foo, Foo, Foo, Foo, ... Foo]`.

@horiuchi I don't think a "threshold" is the answer, as that would be different for anyone using the library. I more meant, is there a better/fancier way to do this in Typescript". The answer is probably "no", in that case I think there's no way around having `maxItems` of tuples in the array type.

**Pull request merged**
