### PR TITLE
Feature: support for `additionalItems`

### LINKED ISSUE #481: Feature: support for `additionalItems`
Hi, here's the next contribution.

This adds support for `additionalItems` by:
- adding an optional 4th `additionalItems` argument to the `buildTupleTypeNode` astBuilder function, which will pass the additionalItems schema instead of the `any` keyword if present
- update `generateArrayTypeProperty` function to include, after normalization & type property generation, the `additionalItems` type to `buildSimpleArrayNode` & `buildTupleTypeNode` branches
- add corresponding `array` & `tuple` tests
- update the feature table

#480

### PR DESCRIPTION
**Pull request by medfreeman**
closes #481

### CODE REVIEW

**Comment by horiuchi** [comment]
@medfreeman Thank you again for your contribution! 👍 

LGTM!
The only thing is, does it support the `additionalItems: false` pattern?
It was not included in the test pattern for unit tests.

**Comment by medfreeman** [comment]
@horiuchi thanks to you!

After testing, no it doesn't.
I am currently adding tests and correcting the behavior.

**Comment by medfreeman** [comment]
Ok, done.
Please have a look at the additional tests, so i'm sure we agree on the results.

**Comment by horiuchi** [comment]
@medfreeman Good work! 👍

**Pull request merged**
